blank_issues_enabled: false
contact_links:
- name: 💬 Playback Discord Server
  about: Join the community to ask questions, discuss ideas, or get support related to Playback.
  url: https://discord.gg/mUhRUD8AM
