#pragma once

#include <Windows.h>

#ifndef D3D12_RAYTRACING_GEOMETRY_DESC
#define D3D12_RAYTRACING_GEOMETRY_DESC D3D12_RAYTRACING_GEOMETRY_DESC
#endif

#ifndef D3D12_FEATURE_DATA_ARCHITECTURE
#define D3D12_FEATURE_DATA_ARCHITECTURE D3D12_FEATURE_DATA_ARCHITECTURE
#endif

#ifndef D3D12_FEATURE_DATA_D3D12_OPTIONS
#define D3D12_FEATURE_DATA_D3D12_OPTIONS D3D12_FEATURE_DATA_D3D12_OPTIONS
#endif

#include <d3d12.h>
